"""tenant scoped schema

Revision ID: 0001_tenant_scoped_schema
Revises:
Create Date: 2026-05-13

This initial migration creates the current SQLAlchemy metadata. Local demo mode
still supports SQLAlchemy create_all() for SQLite compatibility, but production
deployments can now run a real Alembic upgrade path and then add follow-up
autogenerated revisions as the schema evolves.
"""

from __future__ import annotations

from alembic import op

from src.models import Base


revision = "0001_tenant_scoped_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
